[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/api/*"
  to = "https://backend.spacetechs.net/api/:splat"
  status = 200
  force = true